### PR TITLE
Fix deserialization endianness

### PR DESCRIPTION
**Pull request by Acuadros95**
Integration tests running on https://github.com/eProsima/Micro-XRCE-DDS/pull/162 :heavy_check_mark:

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Linux/598/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Windows/599/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Linux/600/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Windows/601/)

**Review by pablogs9 — APPROVED** [review]

**Comment by ted-miller** [comment]
Is this only expected to build in a Rolling environment?
I'm attempting to build in Humble and getting an error regarding usage of `rosidl_get_zero_initialized_type_hash`. The only google reference I found to that function is in some [Rolling document.](https://docs.ros.org/en/ros2_packages/rolling/api/rosidl_runtime_c/generated/function_type__hash_8h_1a4bf016099c06e8924ba1ce5ea8c606a3.html)

**Comment by gavanderhoorn** [comment]
@ted-miller: I believe the problem is on (y)our side. The default branch on `micro-ROS-Agent` is `iron`. You should be able to switch to the `humble` branch using `git checkout humble`.

**Comment by ted-miller** [comment]
Yep, I cloned the wrong branch.

My initial test looks promising. But I ran into additional issues in our code that is preventing me from fully testing. I'll continue debug next week.

**Comment by Acuadros95** [comment]
@gavanderhoorn @ted-miller Any update? Can we merge this fix?

**Comment by gavanderhoorn** [comment]
Apologies for my/our delayed response @Acuadros95.

I haven't been able to test (any) more, but I believe @ted-miller reported he was able to get at least the initial Client<->Agent connection to succeed.

If these changes only affect the big-endian side, I'd suggest to merge, as it would seem it's currently in a non-working state, and this PR gets it at least closer to a working state, if not already a working state.

Thanks again for addressing this, and I owe you a beer -- if we ever run into you at a ROSCon or similar event. :beer:

**Comment by Acuadros95** [comment]
> If these changes only affect the big-endian side, I'd suggest to merge, as it would seem it's currently in a non-working state, and this PR gets it at least closer to a working state, if not already a working state.

The PR covers all the endianness communication issues, should be at a working state.

> Thanks again for addressing this, and I owe you a beer -- if we ever run into you at a ROSCon or similar event.

:beers: !

**Comment by gavanderhoorn** [comment]
@Acuadros95: any tips on what would be the easiest way to build a docker image for the micro-ROS Agent which includes these changes?

I've been manually editing super build `.cmake` files so far.

Would that be the way to do it until a new release of Micro XRCE-DDS Agent is cut?

**Comment by pablogs9** [comment]
Hello @gavanderhoorn, I guess that the last micro-ROS Agent has these changes. In any case I have retriggered the generation: https://github.com/micro-ROS/docker/actions/workflows/generate_agent_docker.yml

**Comment by gavanderhoorn** [comment]
Ah, ok. I got confused by the merge target for this PR (set to `develop`).

> In any case I have retriggered the generation

thanks for that :+1:

**Pull request merged**
