### PR TITLE
Fix fragmentation [7903]

### PR DESCRIPTION
**Pull request by julibert**
This PR is related to https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/142.
It introduces some changes made during the testing of the aforementioned PR.

Before merge:
- [x] Merge https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/142.
- [x] Change `_microxrcedds_client_tag` to develop.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Linux/167/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Windows/166/)

**Comment by pablogs9** [comment]
Please rebase onto develop and change destination branch

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Linux/172/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Windows/171/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Linux/173/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Windows/172/)

**Comment by julibert** [comment]
Rebase done!

**Pull request merged**
