### PR TITLE
colcon.pkg

### PR DESCRIPTION
**Pull request by julibert**
This PR adds the colcon.pkg file.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Linux/166/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS-Agent%20Manual%20Windows/165/)

**Comment by pablogs9** [comment]
Please:
 - merge https://github.com/micro-ROS/micro-ros-build/pull/96 before this PR
 -  update `dashing` to `develop` in this repo after this PR

**Comment by julibert** [comment]
Done!

**Comment by pablogs9** [comment]
Can you move the tag @julibert ?

**Pull request merged**
